[2022-08-11 05:57:33,361] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Create_snowflake_database manual__2022-08-11T05:57:31.582348+00:00 [queued]>
[2022-08-11 05:57:33,367] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Create_snowflake_database manual__2022-08-11T05:57:31.582348+00:00 [queued]>
[2022-08-11 05:57:33,368] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 05:57:33,370] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-11 05:57:33,370] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 05:57:33,379] {taskinstance.py:1397} INFO - Executing <Task(SnowflakeOperator): Create_snowflake_database> on 2022-08-11 05:57:31.582348+00:00
[2022-08-11 05:57:33,386] {standard_task_runner.py:52} INFO - Started process 18111 to run task
[2022-08-11 05:57:33,389] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V2', 'Create_snowflake_database', 'manual__2022-08-11T05:57:31.582348+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpzv2_0t_z', '--error-file', '/tmp/tmp84u4thcr']
[2022-08-11 05:57:33,391] {standard_task_runner.py:80} INFO - Job 214: Subtask Create_snowflake_database
[2022-08-11 05:57:33,443] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V2.Create_snowflake_database manual__2022-08-11T05:57:31.582348+00:00 [running]> on host c9fcec21ee59
[2022-08-11 05:57:33,510] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V2
AIRFLOW_CTX_TASK_ID=Create_snowflake_database
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T05:57:31.582348+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T05:57:31.582348+00:00
[2022-08-11 05:57:33,515] {snowflake.py:118} INFO - Executing: 
create or replace database us_food_nutrition;
use database us_food_nutrition;
use schema us_food_nutrition.public;

create or replace warehouse food_nutrition_wh with
  warehouse_size='X-SMALL'
  auto_suspend = 180
  auto_resume = true
  initially_suspended=true;

use warehouse food_nutrition_wh;
[2022-08-11 05:57:33,527] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 05:57:33,532] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 05:57:33,534] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 05:57:33,536] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 05:57:34,628] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 05:57:34,802] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:34,803] {snowflake.py:328} INFO - Running statement: create or replace database us_food_nutrition;, parameters: None
[2022-08-11 05:57:34,804] {cursor.py:715} INFO - query: [create or replace database us_food_nutrition;]
[2022-08-11 05:57:35,193] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:35,195] {snowflake.py:338} INFO - Statement execution info - {'status': 'Database US_FOOD_NUTRITION successfully created.'}
[2022-08-11 05:57:35,196] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 05:57:35,198] {snowflake.py:343} INFO - Snowflake query id: 01a635c5-0004-2875-001e-0007000350ca
[2022-08-11 05:57:35,200] {snowflake.py:328} INFO - Running statement: use database us_food_nutrition;, parameters: None
[2022-08-11 05:57:35,201] {cursor.py:715} INFO - query: [use database us_food_nutrition;]
[2022-08-11 05:57:35,495] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:35,497] {snowflake.py:338} INFO - Statement execution info - {'status': 'Statement executed successfully.'}
[2022-08-11 05:57:35,500] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 05:57:35,502] {snowflake.py:343} INFO - Snowflake query id: 01a635c5-0004-2870-001e-000700030312
[2022-08-11 05:57:35,503] {snowflake.py:328} INFO - Running statement: use schema us_food_nutrition.public;, parameters: None
[2022-08-11 05:57:35,504] {cursor.py:715} INFO - query: [use schema us_food_nutrition.public;]
[2022-08-11 05:57:35,808] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:35,820] {snowflake.py:338} INFO - Statement execution info - {'status': 'Statement executed successfully.'}
[2022-08-11 05:57:35,825] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 05:57:35,831] {snowflake.py:343} INFO - Snowflake query id: 01a635c5-0004-286b-001e-0007000312c2
[2022-08-11 05:57:35,834] {snowflake.py:328} INFO - Running statement: create or replace warehouse food_nutrition_wh with
  warehouse_size='X-SMALL'
  auto_suspend = 180
  auto_resume = true
  initially_suspended=true;, parameters: None
[2022-08-11 05:57:35,835] {cursor.py:715} INFO - query: [create or replace warehouse food_nutrition_wh with warehouse_size='X-SMALL' auto...]
[2022-08-11 05:57:36,266] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:36,270] {snowflake.py:338} INFO - Statement execution info - {'status': 'Warehouse FOOD_NUTRITION_WH successfully created.'}
[2022-08-11 05:57:36,273] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 05:57:36,275] {snowflake.py:343} INFO - Snowflake query id: 01a635c5-0004-2875-001e-0007000350ce
[2022-08-11 05:57:36,277] {snowflake.py:328} INFO - Running statement: use warehouse food_nutrition_wh;, parameters: None
[2022-08-11 05:57:36,279] {cursor.py:715} INFO - query: [use warehouse food_nutrition_wh;]
[2022-08-11 05:57:36,463] {cursor.py:739} INFO - query execution done
[2022-08-11 05:57:36,468] {snowflake.py:338} INFO - Statement execution info - {'status': 'Statement executed successfully.'}
[2022-08-11 05:57:36,471] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 05:57:36,476] {snowflake.py:343} INFO - Snowflake query id: 01a635c5-0004-2870-001e-000700030316
[2022-08-11 05:57:36,479] {connection.py:557} INFO - closed
[2022-08-11 05:57:36,637] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 05:57:36,883] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V2, task_id=Create_snowflake_database, execution_date=20220811T055731, start_date=20220811T055733, end_date=20220811T055736
[2022-08-11 05:57:36,925] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 05:57:36,955] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
