[2022-08-11 06:18:44,043] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V3.load_into_monthly_sales_table manual__2022-08-11T00:43:37.451055+00:00 [queued]>
[2022-08-11 06:18:44,093] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V3.load_into_monthly_sales_table manual__2022-08-11T00:43:37.451055+00:00 [queued]>
[2022-08-11 06:18:44,094] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 06:18:44,096] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2022-08-11 06:18:44,097] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 06:18:44,165] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_into_monthly_sales_table> on 2022-08-11 00:43:37.451055+00:00
[2022-08-11 06:18:44,212] {standard_task_runner.py:52} INFO - Started process 20284 to run task
[2022-08-11 06:18:44,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V3', 'load_into_monthly_sales_table', 'manual__2022-08-11T00:43:37.451055+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpclfpu18v', '--error-file', '/tmp/tmpqdod28qs']
[2022-08-11 06:18:44,278] {standard_task_runner.py:80} INFO - Job 350: Subtask load_into_monthly_sales_table
[2022-08-11 06:18:44,490] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V3.load_into_monthly_sales_table manual__2022-08-11T00:43:37.451055+00:00 [running]> on host c9fcec21ee59
[2022-08-11 06:18:44,656] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V3
AIRFLOW_CTX_TASK_ID=load_into_monthly_sales_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:43:37.451055+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T00:43:37.451055+00:00
[2022-08-11 06:18:44,658] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 06:18:44,676] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 06:18:44,686] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 06:18:44,692] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 06:18:44,693] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 06:18:45,954] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 06:18:46,257] {cursor.py:739} INFO - query execution done
[2022-08-11 06:18:46,258] {snowflake.py:328} INFO - Running statement: COPY INTO public.monthly_sales
FROM @s3_stage/
files=('monthly-sales-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 06:18:46,259] {cursor.py:715} INFO - query: [COPY INTO public.monthly_sales FROM @s3_stage/ files=('monthly-sales-staged.csv'...]
[2022-08-11 06:18:46,764] {cursor.py:739} INFO - query execution done
[2022-08-11 06:18:46,765] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/monthly-sales-staged.csv', 'status': 'LOAD_SKIPPED', 'rows_parsed': 0, 'rows_loaded': 0, 'error_limit': None, 'errors_seen': 1, 'first_error': 'File was loaded before.', 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-11 06:18:46,766] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 06:18:46,767] {snowflake.py:343} INFO - Snowflake query id: 01a635da-0004-2869-001e-000700034282
[2022-08-11 06:18:46,768] {connection.py:557} INFO - closed
[2022-08-11 06:18:46,938] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 06:18:47,155] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-11 06:18:47,199] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V3, task_id=load_into_monthly_sales_table, execution_date=20220811T004337, start_date=20220811T061844, end_date=20220811T061847
[2022-08-11 06:18:47,342] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 06:18:47,508] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
